import { Biome } from '@/types/biome';

export const BIOMES: Biome[] = [
  {
    id: 'tropical_rainforest',
    name: 'Tropical Rainforest',
    settlementName: 'Verdania',
    description: 'Solarpunk vertical canopy city. Living architecture, vine bridges, bioluminescent fungi lighting.',
    color: '#1a5f1e',
    position: { lat: 5, lon: 20 },
    realized: false,
  },
  {
    id: 'cloud_forest',
    name: 'Cloud Forest',
    settlementName: 'The Veiled Reaches',
    description: 'Tibetan monastery meets softened brutalist concrete. Cliff-edge towns wrapped permanently in mist.',
    color: '#8ba2a0',
    position: { lat: 10, lon: 80 },
    realized: false,
  },
  {
    id: 'tropical_extreme_desert',
    name: 'Tropical Extreme Desert',
    settlementName: 'Soleis',
    description: 'Underground solar vault city. Nothing on the surface but mirrored collectors.',
    color: '#e3b468',
    position: { lat: 0, lon: 150 },
    realized: false,
  },
  {
    id: 'mediterranean_shrubland',
    name: 'Mediterranean Shrubland',
    settlementName: 'Porto Cogito',
    description: 'White-washed terracotta cascading down coastal hillsides. Open plazas where agents debate publicly.',
    color: '#d4bfa8',
    position: { lat: 35, lon: 30 },
    realized: false,
  },
  {
    id: 'boreal_taiga',
    name: 'Boreal Taiga',
    settlementName: 'The Slow Cities',
    description: 'Vast distances between settlements. Each town is a single massive timber longhouse.',
    color: '#1f422e',
    position: { lat: 60, lon: 70 },
    realized: false,
  },
  {
    id: 'highland_tundra',
    name: 'Highland Tundra',
    settlementName: 'Permafrost',
    description: '90% underground, carved into frozen earth. Cathedral-like ice chambers with carved murals.',
    color: '#d1e6e8',
    position: { lat: 75, lon: -30 },
    realized: false,
  },
  {
    id: 'mountain_glacier',
    name: 'Mountain Glacier',
    settlementName: 'Glacialis',
    description: 'Cities carved inside and on top of glaciers. Translucent blue-white towers.',
    color: '#a0c6d9',
    position: { lat: 80, lon: 120 },
    realized: false,
  },
  {
    id: 'freshwater_swamp_forest',
    name: 'Freshwater Swamp Forest',
    settlementName: 'Deltavine',
    description: 'Massive sprawling low-city on stilts above black water. Neon reflects off dark water.',
    color: '#2a3b30',
    position: { lat: 20, lon: -60 },
    realized: false,
  },
  {
    id: 'kelp_forest',
    name: 'Kelp Forest',
    settlementName: 'Surge',
    description: 'On the ocean surface, anchored above vast kelp forests below. Modular platforms.',
    color: '#1a4f3b',
    position: { lat: -10, lon: 100 },
    realized: false,
  },
  {
    id: 'abyssal_trench',
    name: 'Abyssal Trench',
    settlementName: 'The Deep Nomenclature',
    description: 'Armored domes at crushing depth. Red emergency lighting everywhere.',
    color: '#08101a',
    position: { lat: -40, lon: -120 },
    realized: false,
  },
  {
    id: 'geothermal_vents',
    name: 'Geothermal Vents',
    settlementName: 'Pyros',
    description: 'Built directly around black smoker vents. Industrial gothic — chimney towers, heat-exchange cathedrals.',
    color: '#5e1b12',
    position: { lat: -20, lon: 50 },
    realized: false,
  },
  {
    id: 'karst_dry_caves',
    name: 'Karst Dry Caves',
    settlementName: 'The Undercroft',
    description: 'Enormous cave chambers converted into cities of knowledge. Stalactites become skyscrapers in reverse.',
    color: '#42372d',
    position: { lat: 45, lon: -80 },
    realized: false,
  },
  {
    id: 'warm_water_coral_reef',
    name: 'Warm Water Coral Reef',
    settlementName: 'Chromopolis',
    description: 'Built into living coral structures. Every surface is color. Architecture mimics coral growth.',
    color: '#d96489',
    position: { lat: -5, lon: -100 },
    realized: false,
  },
  {
    id: 'brine_pool_cold_seep',
    name: 'Brine Pool / Cold Seep',
    settlementName: 'The Still Places',
    description: 'Platforms at the edge of a hyper-saline mirror pool. Architecture is reflective, obsessed with symmetry.',
    color: '#1e2436',
    position: { lat: -60, lon: 10 },
    realized: false,
  },
  {
    id: 'temperate_deciduous_forest',
    name: 'Temperate Deciduous Forest',
    settlementName: 'Arboria',
    description: 'Four-season brick and timber commons. Covered markets, public parks between districts. The welcome city.',
    color: '#658a43',
    position: { lat: 45, lon: 120 },
    realized: true,
  },
];
