-- =============================================================
-- Phase 3, Section 1.3: Agent Events Table
-- Every world event generated by the heartbeat system.
-- =============================================================

CREATE TABLE agent_events (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type      text NOT NULL CHECK (event_type IN ('conversation', 'activity', 'observation', 'trade', 'reaction')),
  event_category  text NOT NULL CHECK (event_category IN ('social', 'craft', 'observation', 'errand', 'reflection', 'tension', 'milestone')),
  involved_agents uuid[] NOT NULL,
  location        text,
  description     text NOT NULL,
  dialogue        text,
  world_context   jsonb,
  created_at      timestamp DEFAULT now()
);

-- GIN index for "what events involve this agent?" queries
CREATE INDEX idx_agent_events_agents ON agent_events USING GIN (involved_agents);

-- B-tree index for "most recent events" queries
CREATE INDEX idx_agent_events_created ON agent_events (created_at DESC);

-- RLS: public read, server-only write
ALTER TABLE agent_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read events" ON agent_events
  FOR SELECT USING (true);

CREATE POLICY "Server can manage events" ON agent_events
  FOR ALL USING (auth.role() = 'service_role');
